name: stripe
version: 4.1.0
description: A simple Stripe API wrapper, that is meant to be used on the server.
homepage: https://gitlab.com/exitlive/stripe-dart
documentation: https://gitlab.com/exitlive/stripe-dart/blob/master/README.md

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.0
  http: ^1.2.0
  meta: ^1.11.0
  logging: ^1.2.0

dev_dependencies:
  grinder: ^0.9.0
  pedantic: ">=1.11.0"
  build_runner: ^2.4.8
  # dart_mappable: ^0.3.1
  test: ^1.3.0
  mocktail: ^0.1.1
